### ISSUE TITLE
[question] Does Apptainer work on FreeBSD ?

### ISSUE THREAD

**Issue by yurivict** [apptainer/apptainer#1008]

**Comment by GodloveD** [comment]
It's definitely not supported. As to whether or not it works, I can't say for certain because I don't know enough about the freebsd kernel to know if it supports namespaces in the same way that the linux kernel does.  I spun up a freebsd vm and spent a little time trying but I can't get `mconfig` to recognize the go compiler (probably because it is reporting freebsd instead of linux in the version string).

**Comment by yurivict** [comment]
FreeBSD uses jails for containerization. Namespaces aren't supported AFAIK.

**Comment by GodloveD** [comment]
I don't know if anybody else wants to weigh in on this (@cclerget ? @DrDaveD ?).  But I think this is the summary:

If it works, that is a happy (and unlikely) coincidence.  There has been no effort to get it working on FreeBSD.  And there is no planned development effort to port this to FreeBSD.

**Comment by DrDaveD** [comment]
Agreed.
