### ISSUE TITLE
failed to add as session directory: path . is not an absolute path

### ISSUE THREAD

**Issue by Timmmm** [apptainer/apptainer#1136]
### Version of Apptainer

```
1.1.6-1.el8
```

### Expected behavior

Apptainer should work.

### Actual behavior

I get this error:

```
apptainer shell sail.sif
INFO:    Cleanup error: while unmounting /home/COMPANY/tim/local/apptainer/x86_64/var/apptainer/mnt/session/final directory: no such file or directory, while unmounting /home/COMPANY/tim/local/apptainer/x86_64/var/apptainer/mnt/session/rootfs directory: no such file or directory
FATAL:   container creation failed: failed to add  as session directory: path . is not an absolute path
```

### Steps to reproduce this behavior

This is a re-opening of https://github.com/apptainer/singularity/issues/6242 - which says that non-standard home directories cause the issue, and I also have a non-standard home directory so that seems to be consistent.

### What OS/distro are you running

RHEL 8.6

### How did you install Apptainer

```
curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s - ~/local/apptainer
```

**Comment by GodloveD** [comment]
Looks like @cclerget was working on this issue before it was moved.

**Comment by DrDaveD** [comment]
I tried reproducing this on rockylinux 8.7 VM and did not see a problem.   I did the commands:
```
sudo mkdir /home/COMPANY
sudo adduser -d /home/COMPANY/tim -m tim
sudo su - tim
mkdir local
curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s - ~/local/apptainer
PATH=$HOME/local/apptainer/bin:$PATH
apptainer pull docker://rockylinux:8
apptainer shell rockylinux_8.sif
```
So the "non-standard" directory alone is not the cause of the problem.  We need more information about how to reproduce it, or we need you to do more debugging on your own as we asked the person in the previous issue.  For example, what is the home directory filesystem type?   Does it happen with all sif files, or is there something about that sif file that triggers it?  Is winbindd in use, as was identified in that other issue and also in related issue sylabs/singularity#696?  In both of those issues the person submitting the ticket apparently lost interest, so no solution has yet been found.

**Comment by Timmmm** [comment]
Unfortunately I didn't set this system up so I'm not sure about better reproduction, but I'm happy to do more debugging.

> what is the home directory filesystem type

The home filesystem appears to be XFS:

    /dev/mapper/system-home on /home type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=128,noquota)
    $ stat --file-system --format=%T ~
    xfs

> Does it happen with all sif files, or is there something about that sif file that triggers it?

Appears to be all sif files. I tried another one and it also failed. Both work on a different machine.

> Is winbindd in use

Yes!

```
$ ps -A | grep winbindd
   2128 ?        00:00:10 winbindd
   2177 ?        00:00:00 winbindd
   2178 ?        00:00:00 winbindd
   2734 ?        00:00:01 winbindd
   2740 ?        00:00:00 winbindd
```

That can't be a coincidence. Also sshd is using PAM & Kerberos for authentication. I'm not sure if that would make any difference.

**Comment by jcampos79** [comment]
Hi, I am having same problem here.

I am running CentOS9 and RockyLinux 9 , Apptainer installed from official repos:

`apptainer version 1.1.6-1.el9`

In my tests, all users from AD fails to execute, but,  running same containers with local user works fine on same machines.

from the debug:

- AD user:
`
...
DEBUG   [U=2001215,P=18931]addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=2001215,P=18931]addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=2001215,P=18931]addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=2001215,P=18931]umount()                      Umount /var/apptainer/mnt/session/final
DEBUG   [U=2001215,P=18931]umount()                      Umount /var/apptainer/mnt/session/rootfs
INFO    [U=2001215,P=18931]CleanupContainer()            Cleanup error: while unmounting /var/apptainer/mnt/session/final directory: no such file or directory, while unmounting /var/apptainer/mnt/session/rootfs directory: no such file or directory
FATAL   [U=2001215,P=18931]Master()                      container creation failed: failed to add  as session directory: path . is not an absolute path
`

- local user:
`
...
DEBUG   [U=1001,P=19036]   addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=1001,P=19036]   addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=1001,P=19036]   addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=1001,P=19036]   addHomeStagingDir()           Staging home directory (/home/jcampos) at /var/apptainer/mnt/session/home/jcampos
DEBUG   [U=1001,P=19036]   addHomeMount()                Adding home directory mount [/var/apptainer/mnt/session/home/jcampos:/home/jcampos] to list using layer: underlay
DEBUG   [U=1001,P=19036]   addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=1001,P=19036]   addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=1001,P=19036]   addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=1001,P=19036]   addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=1001,P=19036]   addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=1001,P=19036]   addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=1001,P=19036]   addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=1001,P=19036]   addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=1001,P=19036]   addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=1001,P=19036]   create()                      Mount all
DEBUG   [U=1001,P=19036]   mountGeneric()                Mounting tmpfs to /var/apptainer/mnt/session
DEBUG   [U=1001,P=19036]   func2()                       Starting image driver fuseapps
...`

Hope this will be useful, I can perform more tests if required.

**Comment by DrDaveD** [comment]
Ok so for some reason `addHomeStagingDir()` does not get called.  I do not have users coming from AD so there's no way for me to debug and find a solution for it, and I don't think @cclerget does either.  If you could put in further debug statements and eventually come up with a pull request to fix it, that would be awesome.

**Comment by mdehollander** [comment]
Running here in the same error, where homes are located in a /home/domain/username directory for AD users.

Using the `--home` flag also worked, but I also found out singularity-ce does not have this issue (standard with suid). Therefore also installed apptainer-suid and now both build with apptainer and the `shell/exec` commands find and mount the home folder without extra configuration. 

So, does `addHomeStagingDir()` need the suid binary?

**Comment by DrDaveD** [comment]
> So, does `addHomeStagingDir()` need the suid binary?

Not as far as I can tell from the code, I don't see how it makes a difference.  We'll need someone's help to debug this, since we cannot reproduce it.  Can you look at the debug output, see if you are seeing the same behavior as jcampos79, and add some more debug statements to narrow it down?

**Comment by mdehollander** [comment]
I see where I can help, because I am not an expert on this. But I see the same as jcampos79. If I execute cowsay with apptainer-suid installed and afterwards remove it, you can find the difference of the debug log here: https://bin.disroot.org/?08b89353a71e20ae#5d5e2NNRZCQhib964HAJveXgR9DeEzGuSSdX8c6XvHG8

The `<` part is for the first run with apptainer-suid and a working home mount and the second part starting with `>` is without it and a crashing `shell/exec` command.
In the apptainer without suid debug log I see mentions of `squashfuse_ll` where in the apptainer-suid it is not present. And fuse is used for mounting, can this be a lead?

**Comment by DrDaveD** [comment]
So you are seeing the same behavior according to the debug logs.  Using `squashfuse_ll` without suid is expected, but I don't see how it would impact this.

I see now that the error is coming from inside [`addHomeStagingDir()`](https://github.com/apptainer/apptainer/blob/v1.1.6/internal/pkg/runtime/engine/apptainer/container_linux.go#L1708), because the source string is empty.  The source string comes from [`getHomePaths()`](https://github.com/apptainer/apptainer/blob/v1.1.6/internal/pkg/runtime/engine/apptainer/container_linux.go#L1681).  That string comes from [`CurrentOriginal()`](https://github.com/apptainer/apptainer/blob/v1.1.6/internal/pkg/util/user/identity_unix.go#L61).  That does do something different in unprivileged mode in the [`namespaces.HostUID()`](https://github.com/apptainer/apptainer/blob/v1.1.6/pkg/util/namespaces/user_linux.go#L69) function, but that just does a uid translation sometimes, it doesn't look up the password entry to find the home directory.  The problem must be in [`GetPwUID()`](https://github.com/apptainer/apptainer/blob/v1.1.6/internal/pkg/util/user/identity_unix.go#L33) which calls [`lookupUnixUid()`](https://github.com/apptainer/apptainer/blob/v1.1.6/internal/pkg/util/user/cgo_lookup_unix.go#L105) which just calls the system call to read from the password file.

So that makes me think there's maybe a problem with the password file in the container when using AD in non-suid mode, maybe the pasword file's home directory is empty. So if you start in non-suid mode and with a --home option, look in for your user id's entry in /etc/passwd.  Does it show a home directory?

**Comment by DrDaveD** [comment]
Wait, that's not a good test because that will just override the `/etc/passwd` entry.  Instead, cd to somewhere outside of your home directory (e.g. `/tmp/`) and run it with the `--no-home` option.  Then check your user entry in `/etc/passwd`.

**Comment by mdehollander** [comment]
Thanks for looking at the debug output and your interpretation. If I execute what you suggest I get this:

```
username@server:/tmp$ apptainer shell --home /home/domain/username/ lolcow.sif 
INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
WARNING: user: lookup userid 22222: no such file or directory
WARNING: user: lookup userid 22222: no such file or directory
```

From the debug log:
```
VERBOSE [U=22798,P=125706] Passwd()                      Checking for template passwd file: /var/lib/apptainer/mnt/session/rootfs/etc/passwd
VERBOSE [U=22798,P=125706] Passwd()                      Creating passwd content
WARNING [U=22798,P=125706] addIdentityMount()            user: lookup userid 22222: no such file or directory
VERBOSE [U=22798,P=125706] Group()                       Checking for template group file: /var/lib/apptainer/mnt/session/rootfs/etc/group
VERBOSE [U=22798,P=125706] Group()                       Creating group content
WARNING [U=22798,P=125706] addIdentityMount()            user: lookup userid 22222: no such file or directory
```
My user is not listed in `/etc/passwd`, as expected I would say because it would not store AD information, but is used only for local user if I am correct. 

I also see you have referenced this is on the singularity repo before and not resolved or followed-up: https://github.com/sylabs/singularity/issues/696 This describes exactly what is happening here as well, but then with singularity-without-suid installed. We also use winbind over here. So this issue also still exist in singularity-without-suid.

**Comment by DrDaveD** [comment]
I think that we can't expect winbindd to be running inside the container so we would need to copy it into /etc/passwd.  Please verify that with `--no-home` you get the same behavior of no home directory in /etc/passwd inside the container.  Then if you can run it with setuid root I'd like to see if the user gets into /etc/passwd.

**Comment by mdehollander** [comment]
Yes, indeed winbind is not present in the container.

> Please verify that with --no-home you get the same behavior of no home directory in /etc/passwd inside the container.
Nothing with the username is in `/etc/passwd` in this case

> Then if you can run it with setuid root I'd like to see if the user gets into /etc/passwd.
Yes, then the user is listed in `/etc/passwd`

@SamStudio8 wrote in the issue in the singularity thread also something related to this:
>Critically, my user information is not stored in passwd and is fetched through a connect to /var/run/samba/winbindd/pipe. I have tried binding nsswitch.conf and /var/run/samba/winbindd/pipe to the container with a bind path in my singularity.conf to no avail. I don't understand enough about Singularity to reason about why this later step does not behave the same as earlier calls to lookupUnixUid -- is it inside the container context at that time?

**Comment by DrDaveD** [comment]
Ok, we're getting closer.  I'm a bit surprised that there's no /etc/passwd entry at all though; I would have guessed that it would be there but with an empty home directory.

It is very difficult for me to debug this, though, since I can't reproduce it.  The next suggestion I have to try is to see if the library works at all  in an unprivileged user namespace, independent of apptainer.  What do you get from:
```
getent passwd $LOGNAME
unshare -U getent passwd $LOGNAME
unshare -r getent passwd $LOGNAME
```
It's probably not the same library used by go, but it ought to have some parts at least in common.

What do you see with `grep ^passwd /etc/nsswitch.conf`?  I have "winbindd" running on  my personal home Debian system, but I don't have an AD, I just used to share a filesystem over smb.  If I add "winbind" to the passwd line in /etc/nsswitch.conf, I can see with `unshare -r strace getent passwd $LOGNAME` that it is attempting to access some winbind-related libraries.  Ah, interestingly if I run it without `unshare -r` I see t opening `/var/run/samba/winbindd/pipe`, but with `unshare -r` it stops after doing `lstat64("/var/run/samba/winbindd" ...`.  Perhaps it is checking to see if the directory is owned by root, which it won't be in an unprivileged user namespace:
```
$ unshare -r ls -ld /var/run/samba/winbindd
drwxr-xr-x 2 nobody nogroup 60 Sep 21  2022 /var/run/samba/winbindd
```

**Comment by mdehollander** [comment]
Thanks for trying to localize the issue. Although I have full access to debug, it is also difficult for me since I am not an expert in this field.

>  What do you get from:
> 
> getent passwd $LOGNAME
> unshare -U getent passwd $LOGNAME
> unshare -r getent passwd $LOGNAME

On the host system, so not inside a container I get:

```
$ getent passwd $LOGNAME
username:*:22222:11111::/home/domain/username:/bin/bash
$ unshare -U getent passwd $LOGNAME
$ unshare -r getent passwd $LOGNAME
```

Inside the apptainer with suid I see this as well, and in addition the unshare command also return the same.

> What do you see with grep ^passwd /etc/nsswitch.conf?
On the host I get:
```
passwd:         files systemd winbind
```
And inside a container only files.

> Ah, interestingly if I run it without unshare -r I see t opening /var/run/samba/winbindd/pipe, but with unshare -r it stops after doing lstat64("/var/run/samba/winbindd" .... Perhaps it is checking to see if the directory is owned by root, which it won't be in an unprivileged user namespace:
Same here if I run it on the host

If I run the same inside the container with apptainer without there are attempts to write to `/etc/passwd` but those fail. And there are not mentions of winbind: https://bin.disroot.org/?ee93c54baacaace8#5arG2jwLYaRhkt8cFC9WQSFCMxiXhANYddiyoy3tPoWW

With apptainer suid it succeeds writing to `/etc/passwd`: https://bin.disroot.org/?f04c7d23c6a7e280#8XMU2dScxNPwvMqnYFGCFppELSAhFYqSCSsgqRtsZFxL

```
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
lseek(3, 0, SEEK_CUR)                   = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=1293, ...}) = 0
mmap(NULL, 1293, PROT_READ, MAP_SHARED, 3, 0) = 0x7f11890a2000
lseek(3, 1293, SEEK_SET)                = 1293
munmap(0x7f11890a2000, 1293)            = 0
close(3)                                = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(1, "username:x:22222:11111::/home/dom"..., 54username:x:22798:10513::/home/domain/username:/bin/bash
) = 54
exit_group(0)                           = ?
```

Hope this helps.

**Comment by DrDaveD** [comment]
Ok good this confirms that the underlying problem is not in apptainer, it is in the host libraries, since the problem happens even when not running apptainer. 

With those straces you posted, running inside of apptainer, it is not attempting to write to /etc/passwd: it is reading from /etc/passwd and in the second case it writes to stdout as expected.  Those behaviors are both entirely expected and don't have anything to do with the underlying problem.

So, now that we understand the problem, I can think of a workaround that unprivileged apptainer could do: if it fails to read the user's password entry, it could fake one based on $LOGNAME and $HOME environment variables.  I will discuss with other apptainer developers if they think that it is a good idea.

Somebody ought to report this to the winbind developers as well (that is, the samba project).

**Comment by DrDaveD** [comment]
It would be great if you could test it but unfortunately, even though one is built as part of the usual checks, it is only saved when a release is cut.  The easiest thing is probably to follow the debian instructions in INSTALL.md and not build it into a debian package.  If you want to do that there's more instructions in dist/debian/DEBIAN_PACKAGE.md.

**Comment by mdehollander** [comment]
I noticed the 1.2.0 RC deb builds where available to download. I am happy to confirm it works now, so without installing the suid binary.

In the mean time I also tried a different way of installing from source. With [spack](https://www.spack.io) installing from the [main branch](https://packages.spack.io/package.html?name=apptainer) is a oneliner and it installs all depedencies at the same time: `spack install apptainer@main -suid`. By default it compiles `with-suid` but adding `-suid` to the command it runs `--without-suid`.
