### ISSUE TITLE
What's the best solution to get the apptainer run on a scenario like this

### ISSUE THREAD

**Issue by crotoc** [apptainer/apptainer#1562]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

`apptainer version 1.1.5`

### Expected behavior

What did you expect to see when you do...?

`apptainer shell /fs0/chenr6/download/ubuntu.sif`

Get it run

### Actual behavior

What actually happened? Why was it incorrect?
``INFO   : A system administrator may need to enable user namespaces, install                                                                                                                                         
INFO   :   apptainer-suid, or compile with ./mconfig --with-suid                                                                                                                                                    
ERROR  : Failed to create user namespace: user namespace disabled``

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
conda

I have a local machine which is ubuntu 2204 and has root permission. I usually work on a cluster machine which is centos 7 but have no root permission on this cluster. I want to build a sif image to include my scripts and environment. What I am hoping is I am able to install extra apps directly on the cluster if it's necessary so that I don't need to install on local machine and transfer the new image to the cluster server. 

What I have done before:
I built a ubuntu sif on local machine and this sif had conda installed at /mylib/miniconda3/. If I run `singularity run`, it loaded the base env of "/mylib/miniconda3/" by default. To make it feasible, I created a persistent overlay (Env.img) which is writable by anyone. Under this setup, I can install packages by:

`singularity run -e -bind /home --overlay Env.img BASE.sif conda install -y r-base` 

This works well for most of time. But recently I figure that Env.img can not be correctly cleaned. After manipulating the image, the next time I can only access it in readonly mode. Considering 3.7 is old, so I would like to move to apptainer.

I hope the apptainer can do the same thing: I have a BASE.sif and an overlay image (Env.img) and I can install apps to Env.img without root permission.

The problem now is I can not get the apptainer run on server, because it neither has setuid nor user namespaces. I don't think I can ask the manager office to enable these, so I come here to consult you guys about how to achieve this. I am not sure whether I understand the whole thing correctly, please give me some advices. Thanks!

**Comment by DrDaveD** [comment]
Let me see if I understand the question.  The cluster machine you want to run on is centos7, it has a singularity-3.7 installation, but you want to run apptainer.  You have no root privileges and there are no unprivileged user namespaces.  Is that all correct?

If so the only option is to ask the system administrators for help.  They either need to enable unprivileged user namespaces or they need to install a suid version of apptainer.  

Note that since apptainer-1.1.8, the suid version no longer by default allows overlay of ext3 image files, due to a [high severity vulnerability](https://github.com/apptainer/apptainer/security/advisories/GHSA-j4rf-7357-f4cg) inherent in that feature.  That alone should be a sufficient reason to motivate your system administrator to upgrade to apptainer, but you won't be able to use the persistent overlay feature with an ext3 image unless the system administrator re-enables that risky feature or enables unprivileged user namespaces.  There is a [plan](#1411) for 1.3.0 to use FUSE from suid mode which would also re-enable the feature.

**Comment by DrDaveD** [comment]
Since 1.2.0 was just released two days ago, it will be a while until 1.3.0 is released.  I don't recommend waiting that long to deal with the security vulnerability.

**Comment by crotoc** [comment]
It seems like now I have issues of cleaning ext3 overlay image. When I run the image in local drive, it works. But if I copy the overlay image to a net based drive which is maintained by our HPC manager, it throws an error:
FATAL   [U=226488,P=12029] StageOne()                    while loading overlay images: failed to open overlay image /nobackup/cgg/chenr6/sif/RuiEnv.img: while locking ext3 partition from /panfs/accrepfs.vampire\
/nobackup/cgg/chenr6/sif/RuiEnv.img: can't open /panfs/accrepfs.vampire/nobackup/cgg/chenr6/sif/RuiEnv.img for reading, currently in use for writing by another process 

Can you give me a suggestion about how to clean the image correctly as a workaround give 1.3 is not released and our mamager refused to do something? Thanks!

**Comment by DrDaveD** [comment]
That's a different issue, so I suggest creating another github issue.  However, I'm not sure there's anything to do about that other than avoiding the use of overlay, even when 1.3 is ready.
