### ISSUE TITLE
Add checkpointing with DMTCP

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#16]
This is a continuation of apptainer/singularity#468.

**Comment by olifre** [comment]
Since the title of the issue changed in the migration, just adding some discussion points from the original issue:
* Usage of [CRIU](https://criu.org/Main_Page), which also supports live migration (important for migrating long-running MPI processes on HPCs). 
* Checkpointing and restore of MPI processes (see e.g. [this](http://hv.diva-portal.org/smash/get/diva2:1144045/FULLTEXT01.pdf) related work, using CRIU instead of DMTCP to achieve this in a stable manner).

**Comment by PaulCharlton** [comment]
At the moment, checkpoint capability is available via the plugin module from lancium
at [checkpoint plugin](https://github.com/lancium/dmtcp-singularity-plugin)

**Comment by DrDaveD** [comment]
Yes, thanks, we were aware of that but I don't see a link to it in the previous discussion.  It's useful but needs rework because it's only for singularity version < 3.5.

**Comment by PaulCharlton** [comment]
there should also be some discussion and design around checkpointing the GPU state as well
