### ISSUE TITLE
How to avoid the message 'gocryptfs not found, will not be able to use gocryptfs' to systematically appear every time I run a container image?

### ISSUE THREAD

**Issue by airnandez** [apptainer/apptainer#1697]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

```
$ apptainer --version
apptainer version 1.2.2
```

### Expected behavior

I wonder if it is possible to prevent the message below to appear each time I run a container image:

```
INFO:    gocryptfs not found, will not be able to use gocryptfs
```

I am not using `gocryptfs` so it is not not a problem for me if `apptainer` cannot find it.

### Actual behavior

What actually happened? Why was it incorrect?

Each time I run a container image I get the same message:

```
$ apptainer build lolcow.sif docker://ghcr.io/apptainer/lolcow

$ apptainer run lolcow.sif 
INFO:    gocryptfs not found, will not be able to use gocryptfs
...
```
It is not incorrect, but it is inconvenient to get that message every time. I did not find a way to configure the build process to avoid emitting that message or to not look for `gocryptfs`.

### Steps to reproduce this behavior

See above.

### What OS/distro are you running

```sh
$  cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

From source.

**Comment by DrDaveD** [comment]
It's true, there is not a way to configure the build process to do that.  Instead, the way to avoid the warning is to follow the instructions for installing gocryptfs in INSTALL.md.  It just needs to show up in the PATH, so you should be able to for example put it in the same bin directory as the apptainer command.

**Comment by airnandez** [comment]
If Apptainer expects to find `gocryptfs` in `$PATH` I would still get the undesired message if I execute `apptainer` using its absolute path:

```
$ /path/to/apptainer run lolcow.sif
```

That would mean that I would need to ask all the users of my Apptainer installations to modify their `$PATH` to avoid the message.

**Comment by DrDaveD** [comment]
That's true.  I think the easiest thing to do is to use the [install-unprivileged.sh](https://apptainer.org/docs/admin/latest/installation.html#install-unprivileged-from-pre-built-binaries) method instead of compiling from source, because that inserts a wrapper script that adds the location of gocryptfs to the PATH before it runs apptainer.  Could that work for you?  Otherwise if you need to install from source you could perhaps borrow the technique.

Alternatively, if it's important to you to have a compile option to disable the unprivileged encryption option I suggest making a pull request for that.

**Comment by nsheff** [comment]
I'm also facing this issue. I use lots of singularity containers, and I always run them with their absolute paths.

Every time I run any of them it says

INFO:    gocryptfs not found, will not be able to use gocryptfs

I tried adding gocrypts to my path, but it didn't change anything, I guess because I'm using the absolute path to the container?

I'm on a shared cluster environment, so I don't have capacity to re-intall singularity.
Is there any other solution to this annoyance?

**Comment by DrDaveD** [comment]
That indicates an incomplete installation.  You'll need to take that up with your system administrator.

If you have an uncooperative system administrator but user namespaces are enabled, it should be possible for you to use your own copy of apptainer installed with install-unprivileged.sh.

However, putting gocryptfs in your $PATH should also have worked, unless it is a setuid installation of apptainer.   Usually system administrators only install that if they do not have user namespaces enabled.  If that's the case your only recourse will be to get your system admin to complete the installation and add gocryptfs to the apptainer installation.    If it is setuid but user namespaces are also enabled, then adding the `--userns` flag should enable it to recognize the gocryptfs you have in your PATH.

I'm closing this ticket, it should have been closed last year.   If you still have a problem, please create a new ticket with all the details about your host and installation.

**Comment by djhoese** [comment]
For what it's worth, using the environment variable `APPTAINER_QUIET=1` can silence this message. `APPTAINER_SILENT=1` also works. Doing the command line option equivalent does *not* work. Using `APPTAINER_MESSAGELEVEL=-1` also does *not* work. I'm glad I figured this out as my next step was going to be `grep -v`'ing the output.
