### ISSUE TITLE
Unexpected "Relocation not allowed with starter-suid" error when using Apptainer to launch a desktop environment via Open OnDemand

### ISSUE THREAD

**Issue by novosirj** [apptainer/apptainer#1799]
### Version of Apptainer

```
[novosirj@perceval1 output]$ apptainer --version
apptainer version 1.2.4
```

### Expected behavior

Open OnDemand launches Apptainer container-based desktop environment.

### Actual behavior

Log output shows the following error message:

`FATAL:   Relocation not allowed with starter-suid`

### Steps to reproduce this behavior

Open OnDemand is not totally relevant to this issue, but is part of the environment, so I mention it. Here's the `batch_connect` section for this web app:

```
batch_connect:
  script_wrapper: |
    cat << "CTRSCRIPT" > container.sh
    export PATH="$PATH:/opt/TurboVNC/bin"
    %s  
    CTRSCRIPT
 
    module purge
    module load apptainer/1.2.4

    #export SINGULARITY_BINDPATH="/run/munge:/run/munge,/tmp/$ID:/run/user,/projects,/scratch,/cache/sw:/opt/sw,/cache,/cache/home:/home,/projectsp,/projectsn,/projectsc,/etc/slurm"
    export APPTAINER_BINDPATH="/run,/projects,/scratch,/opt/sw,/cache,/cache/home:/home,/projectsp,/projectsn,/projectsc,/etc/slurm"

    apptainer -v exec <%= image %> /bin/bash container.sh
```

### What OS/distro are you running

```
[novosirj@perceval1 output]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

Source code, with an install script that does the following:

```
[novosirj@perceval1 output]$ cat ~/src/build-apptainer-1.2.4.sh 
#!/bin/sh

module purge
module list

# From Singularity documentation:
# Go is a bit finicky about where things are placed. Here is the correct way to build Singularity from source.
#
# $ mkdir -p $GOPATH/src/github.com/sylabs
# $ cd $GOPATH/src/github.com/sylabs
# $ git clone https://github.com/sylabs/apptainer.git
# $ cd apptainer
#
# However, to do this using apptainer-1.2.4.tar.gz, instead of using git, do "tar xf apptainer-1.2.4.tar.gz".
#
# Also, "make test" step requires apptainer to be in the $PATH, however sudo will clear it out of $PATH. First, set a symlink
# somewhere in the $PATH to the target location (eg. ln -s /opt/sw/packages/gcc-4_8/apptainer/1.2.4/bin/apptainer /usr/bin/apptainer).
# This is kludgey and there's probably a better way.
#       = novosirj, 20190215

export VERSION=1.21.3 OS=linux ARCH=amd64 && \
    wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz -O /scratch/novosirj/install-files/go$VERSION.$OS-$ARCH.tar.gz && \
    mkdir /mnt/scratch/novosirj/go-$VERSION && tar -C /mnt/scratch/novosirj/go-$VERSION -xzf /scratch/novosirj/install-files/go$VERSION.$OS-$ARCH.tar.gz

export GOPATH="/mnt/scratch/novosirj/go-$VERSION/go"
export PATH=${PATH}:${GOPATH}/bin

export VERSION=1.2.4 && # adjust this as necessary \
    wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer-${VERSION}.tar.gz -O /scratch/novosirj/install-files/apptainer-${VERSION}.tar.gz && \
    mkdir -p /mnt/scratch/novosirj/apptainer-$VERSION; cd /mnt/scratch/novosirj/apptainer-$VERSION
    tar -xzf /scratch/novosirj/install-files/apptainer-${VERSION}.tar.gz && \
    cd apptainer-${VERSION}

./mconfig --with-suid --prefix=/opt/sw/packages/gcc-4_8/apptainer/${VERSION} \
        --localstatedir=/var \
        && cd builddir ; make -j32 && sudo -E make install && sudo ln -s /opt/sw/packages/gcc-4_8/apptainer/${VERSION}/bin/apptainer /usr/bin/apptainer && make test && sudo rm -f /usr/bin/apptainer
```

(the last part is a little silly, and I've been meaning to come up with a smarter way).

This is based on a script that used to be on the Singularity install guide (maybe still is).

I don't understand why it's complaining about relocation. I am not relocating the install of Apptainer at all. It will always live in `--prefix` and doesn't move. The only thing I can think of is the following:

```
[novosirj@perceval1 output]$ ls -la /opt/sw
lrwxrwxrwx 1 root root 9 Oct 26  2018 /opt/sw -> /cache/sw
```

...or one of the bind mounts inside the container command line that is confusing something somewhere?

**Comment by DrDaveD** [comment]
Indeed it is one of the bind paths that is confusing it.  If I have your `/opt/sw -> /cache/sw` symlink  and use just your mconfig and make commands then a `-B /cache` option causes that error.  With the `-d` debugging option, without `-B /cache` it shows `Install prefix is /opt/sw/packages/gcc-4_8/apptainer/1.2.4` but with `-B /cache` it shows `Install prefix is /cache/sw/packages/gcc-4_8/apptainer/1.2.4`.  It's rather surprising since I would think that these paths should only be looked at on the host and it wouldn't matter what was mounted in the container. 

Along the way I found that a workaround is to turn starter-suid into a symlink:
```
# cd /opt/sw/packages/gcc-4_8/apptainer/1.2.4/libexec/apptainer/bin
# mv starter-suid.real
# ln -s starter-suid.real starter-suid
```
I don't know why.  The reason I tried that was to try to insert an strace command, and so so far I haven't been able to run strace in a failing condition.  Now I'm going to have to insert some custom debugging code.

**Comment by novosirj** [comment]
I think that when I did a bind mount of `/opt/sw` (this would have been on Singularity most likely when I originally set this), I got only the symlink bound in, which is probably why I did that. Thanks for the interesting workaround though. I assume you would expect that not to break anything else?

**Comment by DrDaveD** [comment]
Correct, I don't expect it to break anything else.  The reason why the workaround works is that the [code](https://github.com/apptainer/apptainer/blob/release-1.2/internal/pkg/buildcfg/confgen/gen.go#L140) defaults to using the compiled-in prefix if it doesn't recognize the base name of the executable as `apptainer`, `starter`, or `starter-suid`.  With the symlink the executable name because `starter-suid.real`.  (So I could have replaced it for strace if I had called the real executable `starter-suid` in another directory).

Probably a better workaround is to change the `/opt/sw` in your APPTAINER_BINDPATH to `/opt`.  That then includes the `/opt/sw` symlink inside the mount namespace so the compiled in prefix after following symlinks is the prefix that it finds starter-suid running under. 

 I did find a bug during my investigation and when it is fixed, it will go back to assuming no relocation and so the error will go away even with your original bind path.

**Comment by novosirj** [comment]
In our environment, that would be essentially harmless -- there's nothing that consequential one way or the other in `/opt` in the image or on the host. I can imagine wanting to have something installed in `/opt` in the container under other circumstances though, and presumably that would present a problem.

Is that something that's likely to be fixed in 1.2.5?

**Comment by DrDaveD** [comment]
I was wrong, it wasn't a bug, it had to be that way.  @cclerget may have some other way to avoid the problem you had but meanwhile just figure on including /opt in the bindpath.

**Comment by DrDaveD** [comment]
I thought of a simple way to fix it, now in #1803.

@novosirj why do you have the `--localstatedir=/var` option in your mconfig?  That installs a required directory structure under `/var/apptainer`, outside of the place you normally store packages.  That could cause problems for you. For example if you share the /cache filesystem with multiple machines, you'll need to make sure that the `/var/apptainer` directories get copied to all the machines separately.  Also there's no guarantee that the `/var/apptainer` structure will stay the same between releases.

**Comment by novosirj** [comment]
Thanks, Dave.

`/cache` is on GPFS, and I believe I was told a long time back that for some reason that that space would not be properly supported on that FS type, or that it would be bad to have that as a directory shared between nodes (I can't recall which; this is from awhile back now). I also build Singularity/Apptainer on XFS, for I believe the same reason (again, been awhile).

These are stateless machines, so the tree does go in the image. We could run into trouble on upgrades, but we test them in advance.

**Comment by novosirj** [comment]
@DrDaveD, I just wanted to confirm that this works correctly with no modifications to our setup on 1.2.5.
