### ISSUE TITLE
pgp key folder references sylab

### ISSUE THREAD

**Issue by dcat52** [apptainer/apptainer#197]
### Version of Apptainer:
Apptainer v1.0.0 Release Candidate 1

### Issue
pgp key folder references sylab with the subfolder `sypgp`
```
$ apptainer key list --secret
Private key listing (/home/davis/.apptainer/sypgp/pgp-secret):
```

### How did you install Apptainer
source

**Comment by dcat52** [comment]
Possibly related fix/solution: #46
Depending on how administrators migrate, possibly want to have a check for a `sypgp` folder inside of `.apptainer`

**Comment by DrDaveD** [comment]
> Possibly related fix/solution: #46 Depending on how administrators migrate, possibly want to have a check for a `sypgp` folder inside of `.apptainer`

We wouldn't check for `.apptainer/sypgp` to migrate it, if that's what you're saying; that only affects people who were running a release candidate, and release candidates are allowed to be incompatible with each other.  We would just update the migration function so that `.singularity/sypgp` gets moved into `.apptainer/pgp` or whatever the new name is, and do it as usual only if `.apptainer` doesn't already exist.

**Comment by dcat52** [comment]
That sounds good, I wasn't sure if there was a proper migration procedure or the intent was for people to simply rename the `.singularity` folder to `.apptainer`

**Comment by DrDaveD** [comment]
> That sounds good, I wasn't sure if there was a proper migration procedure or the intent was for people to simply rename the `.singularity` folder to `.apptainer`

Ah, no, there is a proper migration procedure that happens the first time apptainer runs.
