### ISSUE TITLE
executable outside of the container not on PATH 

### ISSUE THREAD

**Issue by darked89** [apptainer/apptainer#2003]
### Version of Apptainer

1.2.5

### Expected behavior
```
APPTAINER_BINDPATH=$HOME/.cargo/bin/ apptainer exec debian.sif rg 

# output expected
ripgrep requires at least one pattern to execute a search
```

### Actual behavior

`FATAL:   "rg": executable file not found in $PATH` 

### Steps to reproduce this behavior

```
sudo apptainer build debian.sif docker://debian
```

### What OS/distro are you running

```sh
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
```

### How did you install Apptainer
deb file

**Comment by GodloveD** [comment]
After you enter the container execute a `echo $PATH`.  I'm not sure but I'm guessing that `$HOME/.cargo/bin/` is the location of `rg`?  Binding it into the container doesn't automatically add it to the `PATH`.  

You probably don't need to bind it at all since it is your home directory and that is already bind mounted by default.  Instead you probably want to use the `APPTAINERENV_APPEND_PATH` or `APPTAINERENV_PREPEND_PATH` environment variables.  Check the [appendix](https://apptainer.org/docs/user/latest/appendix.html#e) for more info.

**Comment by darked89** [comment]
Thank you very much!.

This works as expected:
```
 APPTAINERENV_APPEND_PATH=$HOME/.cargo/bin/ apptainer exec  --home $PWD/bin/ debian.sif rg
```

Would it make sense to move this info from the appendix to the more exposed section of the documentation?

**Comment by GodloveD** [comment]
Maybe.  If you'd like to strengthen the docs pull requests would be greatly appreciated!  
https://github.com/apptainer/apptainer-userdocs
