### ISSUE TITLE
cgroups v2  required when using --sharens option for MPI jobs ?

### ISSUE THREAD

**Issue by denisbertini** [apptainer/apptainer#2128]
Just a question.

When using  apptainer v 1.3.0 to launch MPI jobs using `--sharens`  on `Rocky Linux 8 ` i got the following WARNING/INFO:

```
INFO:    Instance stats will not be available - requires cgroups v2 with systemd as manager.

```
But the job seems to run without any problem.

What this INFO exactly means ? 
Should one expect some problems related to apptainer instances if cgroups v2 is not enabled in the OS ?

**Comment by DrDaveD** [comment]
Under the hood the `--sharens` option uses the `instance` mechanism and that's why you get that message.

It just means that the `apptainer instance stats` command won't work.  If you don't care about that (and it doesn't really make much sense to care about that with `--sharens`) you can ignore the message.  In fact maybe we should hide that message for the `--sharens` case.  @JasonYangShadow what do you think about that?

**Comment by denisbertini** [comment]
so one can safely ignore this message.
Good !
Btw you can hide right now this message by setting the level message to -3 for example.

**Comment by JasonYangShadow** [comment]
> Under the hood the `--sharens` option uses the `instance` mechanism and that's why you get that message.
> 
> It just means that the `apptainer instance stats` command won't work. If you don't care about that (and it doesn't really make much sense to care about that with `--sharens`) you can ignore the message. In fact maybe we should hide that message for the `--sharens` case. @JasonYangShadow what do you think about that?

Sure, will create a PR for this.
