### ISSUE TITLE
Possible security breach 

### ISSUE THREAD

**Issue by rubens21** [apptainer/apptainer#219]
Hi guys, I've never user your app, so I don't know if it is affected by this issue, but I thought you guys would like to know that there is a possible breach on the library `github.com/adigunhammedolalekan/registry-auth` used by your app.

As described on this PR https://github.com/adigunhammedolalekan/registry-auth/pull/4#issuecomment-1030647039 and fixed by this PR https://github.com/lawilog/registry-auth/pull/2, `registry-auth` relies on a query parameter to define the JWT token's subject field (sub). 
It means that you can authenticate using an account, but be authorised as another account because the `Authorizer` interface receives the wrong `Account` name.

I hope it may be helpful.

**Comment by gmkurtzer** [comment]
Hi @rubens21,

Thank you so much for reaching out to us about this! I believe we are only using this package for our E2E tests, so while it isn't a runtime issue, we will take care of it.

Thanks again,
Greg

**Comment by DrDaveD** [comment]
Yes it is only used to make a test docker server in e2e tests in `e2e/internal/e2e/docker_auth_server.go`.  So we can safely wait to upgrade until the PR is merged.

I also thank you @rubens21 for letting us know.  In the future, though, it would be better to send security notices in private to security@apptainer.org instead of making a public issue.

**Comment by rubens21** [comment]
You're welcome, guys.

@DrDaveD, you are right, sorry. I searched for a private way in Github to send this message, but surprisedly there is no way to send this message more privately. 

I didn't think about going to your website, though.
