### ISSUE TITLE
Unable to push to ghcr.io with Apptainer from organization repository

### ISSUE THREAD

**Issue by e-eight** [apptainer/apptainer#2272]
I am trying to build and push Apptainer containers to ghcr.io with Github Actions. While it is working for my personal repository, it is not working for my organization's repository. 

I am using `apptainer push ${{ matrix.changed_file }}.sif oras://ghcr.io/${GITHUB_REPOSITORY}/${{ matrix.changed_file }}:${tag}` to push the images. This works as intended for my personal repository, but for my organization repository I am getting the error `FATAL: Unable to push image to oci registry: could not parse reference: ghcr.io/<org>/<repo>/<container>:latest`

**Comment by DrDaveD** [comment]
This really looks like a github actions question, not an apptainer question.  You might try the apptainer or github action forums to see if anybody could help, or just use extra debugging in your github actions.

**Comment by robertoostenveld** [comment]
I also came across this issue. Let me share here what solved it for me.

For initial testing and development I implemented this https://github.com/robertoostenveld/sandbox-build and was pushing a container to ghcr.io under my personal account. Pushing a container using the GitHub action worked fine. Pushing from the linux command line with `apptainer push lolcow.sif oras://ghcr.io/robertoostenveld/lolcow:0.1`  also worked fine. 

I then copied the [apptainer-build-push](https://github.com/robertoostenveld/sandbox-build/blob/main/.github/workflows/apptainer-build-push.yml) workflow to a repository under an organizational GitHub account, and there it would not work, giving the error `FATAL: Unable to push image to oci registry: could not parse reference`. Furthermore, I got the same error when pushing from the linux command line using

```
apptainer push lolcow.sif oras://ghcr.io/SIESTA-eu/random:0.1
```

After comparing various settings between the two organizations and not finding a significant difference, I realized that the organizational GitHub account had capitals in its name, whereas my personal GitHub account has not. I then changed the namespace  to lowercase and did

```
apptainer push lolcow.sif oras://ghcr.io/siesta-eu/random:0.1
```

which worked without any issues. So it seems that the `could not parse reference` error has to do with uppercase characters in the namespace. I don't know whether this is due to ghcr.io or due to Apptainer, or an interaction between the two.
