### ISSUE TITLE
apptainer build: /.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [apptainer/apptainer#2291]
### Version of Apptainer

 ```console
$ apptainer --version
apptainer version 1.3.2
$ 
 ```

### Expected behavior

Be able to build a CentOS 7 container with `%post` on Ubuntu 22.04.

### Actual behavior

```console
$ cat sample.def 
Bootstrap: docker
From: centos:centos7

%post
	:
$ 
$ 
$ apptainer build sample.sif sample.def 
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
Build target 'sample.sif' already exists and will be deleted during the build process. Do you want to continue? [y/N] y
INFO:    Starting build...
Copying blob 2d473b07cdd5 skipped: already exists  
Copying config 6d42e44a9f done   | 
Writing manifest to image destination
2024/06/19 12:09:18  info unpack layer: sha256:2d473b07cdd5f0912cd6f1a703352c82b512407db6b05b43f2553732b55df3bc
INFO:    Running post scriptlet
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/faked)
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
FATAL:   While performing build: while running engine: exit status 1
$ 
```

### Steps to reproduce this behavior

Use a definition file with a CentOS 7 image with a phony `%post` section. Try to build.

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ 
```

### How did you install Apptainer

Installed the official DEB packages from the PPA:
* https://ppa.launchpadcontent.net/apptainer/ppa/ubuntu/pool/main/a/apptainer/apptainer_1.3.2-1~ubuntu22.04.0+stable1_amd64.deb
* https://ppa.launchpadcontent.net/apptainer/ppa/ubuntu/pool/main/a/apptainer/apptainer-suid_1.3.2-1~ubuntu22.04.0+stable1_amd64.deb

**Comment by DrDaveD** [comment]
This is a limitation of the fakeroot command mapped in from the host.  If you configure /etc/subuid as described in the [admin docs](https://apptainer.org/docs/admin/latest/user_namespace.html#rootless-fakeroot-feature), you will avoid the problem.  Otherwise you can't use the fakeroot command from the host when the container has older libraries.  There is a workaround described in fakeroot mode 3 in the [user docs](https://apptainer.org/docs/user/latest/fakeroot.html), that of using install-unprivileged.sh for your installation.  After the end of life of EL7 next week that will also stop working to build an EL7 container, however, because then it will need to start using EL8 as its base operating system.

It is also possible to tell apptainer build to not try to use the fakeroot command with the undocumented `--ignore-fakeroot-command` option.  However if you try to install anything that does something like a chown, that will then fail.  It's also possible to first install the fakeroot command inside the container's %post section, and then run everything else under that fakeroot.  This option is probably too complicated for most people, however, so it hasn't been documented.

**Comment by DrDaveD** [comment]
Now that more advanced option has been [documented](https://apptainer.org/docs/user/latest/fakeroot.html#fakeroot-inside-def).
