### ISSUE TITLE
How to directly SSH into an apptainer container?

### ISSUE THREAD

**Issue by YanzhaoW** [apptainer/apptainer#2405]
### Version of Apptainer

1.3.1

### Expected behavior

I would like to directly ssh into an apptainer container as a normal user (Without root privilege or setuid).

### Actual behavior

The portmap option requires the sudo permission:
```shell
sudo apptainer instance start --writable-tmpfs \
    --net --network-args "portmap=8080:80/tcp" docker://nginx web2
```
, which can not by done by normal users.

I also tried with reverse ssh tunneling but still get `Connection closed by UNKNOWN port 65535` error.

### Steps to reproduce this behavior

(editted) For container creation:

```shell
apptainer pull image.sif docker://yanzhaowang/geant4_root:latest
apptainer exec -f --overlay file_path image.sif dnf install -y zsh openssh-server
apptainer exec -f --overlay file_path image.sif zsh
```

For reverse ssh tunneling:

1. inside container:
```shell
ssh -R 9000:localhost:22 username@another_server
```
2. in another server
```shell
ssh username@another_server -p 9000
```
3. See the error

### What OS/distro are you running

host: debian 11
container: fedora 39

### How did you install Apptainer

Provided by sysop

**Comment by DrDaveD** [comment]
You haven't supplied the information we need to help you.  Please give step-by-step instructions on how to reproduce your error.

**Comment by YanzhaoW** [comment]
Thanks for the reply

I just added the steps for the container creation. 

This is not a bug report but rather a feature request or a question. In the documentation, I can't see how I could ssh directly into the container without sudo.

If you need more, please tell me what kind of information I should supply to you.

**Comment by DrDaveD** [comment]
Since you are using fakeroot, do you have /etc/subuid set up?  Are there any INFO messages printed when you start apptainer -f?

When I try your commands on an el8 host with /etc/subuid set up, the first ssh command fails for me with
```
Bad owner or permissions on /etc/crypto-policies/back-ends/openssh.config
```
If I instead run zsh without a `-f` option to apptainer, I can ssh out of the container.  However if I try to connect pack through port 9000 on the remote server I don't see your error.  It does give me Permission denied which in this case makes some sense because that host requires kerberos which I don't have set up. 

However, it's clear to me that your first ssh command is forwarding to port 22 on the *host* that apptainer is run on, since the network is shared.  Is that what you intended for it to do?  Why not just run the ssh command on the host instead of inside of apptainer?

**Comment by YanzhaoW** [comment]
> Since you are using fakeroot, do you have /etc/subuid set up? Are there any INFO messages printed when you start apptainer -f?

Yes, I do have INFO messages printed out.

```text
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    Using fakeroot command combined with root-mapped namespace
```

> However, it's clear to me that your first ssh command is forwarding to port 22 on the host that apptainer is run on, since the network is shared. Is that what you intended for it to do?

No, I intended to forwarding a port which the sshd server INSIDE the container is listening to. I also tried with other port number inside the container, like:
```shell
/usr/sbin/sshd -p 12345 -D
```
and I still got the same error.

> Why not just run the ssh command on the host instead of inside of apptainer?

My goal is to directly ssh into the apptainer container from the outside (no sudo) without using `apptainer exec ... zsh/bash` every single time. I have been trying with ssh back tunneling. Therefore, I would have to run ssh command inside the container to create a back tunnel such that I could ssh directly inside to the container from a remote server. But now it seems not to work. 

I would be really appreciated if you could provide some alternatives to achieve the directly ssh connection to the container.

>  It does give me Permission denied which in this case makes some sense because that host requires kerberos which I don't have set up.

Yes, I also saw the error about kerberos from the verbose output of ssh before it gives the `connection closed` error.

Many thanks

**Comment by DrDaveD** [comment]
The fakeroot command is definitely something you want to avoid at runtime since it is also quite slow.  It is needed when you don't have /etc/subuid setup in order to install the ssh package, but have you tried not using `-f` when you run zsh?

**Comment by YanzhaoW** [comment]
Yes, I also tried with my user name without `-f`.

Probably ssh into a container as a non-sudo user should better be done with docker or a virtual machine like podman. If there is no solution to this with apptainer, I would like to close this issue.

Thanks for your help and attention.

**Comment by DrDaveD** [comment]
I haven't been able to reproduce your issue, but it's true that Apptainer is not designed for running services the way that docker & podman are, so you if you have the option to use them you might be better off.  I also note that since Apptainer uses host networking, you could also use ssh from outside the container to port forward to something inside.
