### ISSUE TITLE
`cd` in `%environment` section causes relocation error

### ISSUE THREAD

**Issue by bloer** [apptainer/apptainer#304]
### Version of Singularity:
 ```
 singularity version 3.6.3-1.osg34.el7
 ```
 
 ### Expected behavior
 In `%environment` section, source a relocatable environment file that uses something like
 
 ```
 MYDIR=$(cd $(dirname $0) && pwd -P)
 ```
 
 to locate itself. `cd` is a basic POSIX command and seems like it should work fine.
 
 ### Actual behavior
 I get the following rather uniformative error:
 
 ```
 Singularity runtime parent: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version LIBC_PRIVATE not defined in file libc.so.6 with link time reference
 ```
 
 #### Comments
Behavior appears to image-specific (and maybe host-specific). E.g., if I use the same recipe below with alpine or centos rather than ubuntu it seems to work. I don't have a convenient ubuntu host to see if that would help. Since `cd` works fine in 
 the %runscript` section, it seems like the environment is being called before things are all the way set up.
 
 ### Steps to reproduce this behavior
 Build an image with the following recipe:
 
 ```
 Bootstrap: docker
 From: ubuntu:20.04
 
 %environment
     cd /usr
 ```
 
 then run `singularity shell image.sif`
 
 ### What OS/distro are you running
 ```
 CentOS Linux release 7.5.1804 (Core) 
 ```
 
 ### How did you install Singularity
 Through `yum`, the "osg" repository.

**Comment by DrDaveD** [comment]
Thank you for the report.  I can reproduce this also with apptainer-1.0.0.  With the debug option I can see that it happens when reading `/.singularity.d/env/90-environment.sh` which is the script that gets everything from the `%environment` section.  If I replace `cd /usr` with `pwd` the problem does not happen.

@cclerget can you please take a look?

@bloer Note that osg34 has not been supported for quite some time (and osg35 does not distribute singularity) so the singularity on your system should be upgraded from the current version in epel, which is version 3.8.6.  Version 3.6.4 was a security release, so 3.6.3 should not be run anymore.

**Comment by bloer** [comment]
Thanks @DrDaveD !  I confirm I still have the issue after updating to `singularity version 3.8.6-1.el7`
