### ISSUE TITLE
Apptainer compatibility requirements for SIF containers

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#40]
Apptainer v1.0.0 must build able to build SIF containers which are runnable via legacy Singularity.

Unresolved: should this be default, or enabled by command line switch.

Need: deprecation warnings when legacy features are used

Add E2E tests for validation

Scope of compatibility includes internal filesystem naming structure and the names of injected environment variables

**Comment by cclerget** [comment]
Left this here instead of #41 :

![Screenshot 2021-12-07 at 15-16-05 Apptainer rename by PaulCharlton · Pull Request #3 · apptainer apptainer](https://user-images.githubusercontent.com/3274134/145046173-db5de386-2cc0-4f3e-8e3f-a580a6758f65.png)
![Screenshot 2021-12-07 at 15-15-32 Apptainer rename by PaulCharlton · Pull Request #3 · apptainer apptainer](https://user-images.githubusercontent.com/3274134/145046180-cd3791b7-cf80-4a21-b3b6-37fafb6091db.png)

**Comment by DrDaveD** [comment]
> Unresolved: should this be default, or enabled by command line switch.

It has been resolved that this should be the default.  In fact I believe the decision was to not even have an option to change the format of SIF containers for 1.0.0.

**Comment by PaulCharlton** [comment]
@cclerget we need some new e2e tests which validate the assumed SIF file structure results from our container build process

**Comment by cclerget** [comment]
> @cclerget we need some new e2e tests which validate the assumed SIF file structure results from our container build process

@PaulCharlton is it a request ?

**Comment by PaulCharlton** [comment]
added code for:
 /.singularity.d/Singularity
SINGULARITY_APPNAME
SINGULARITY_SHELL
SINGULARITY_OCI_RUN
