### ISSUE TITLE
Question about the purpose of function `fix_userns_devfuse_fd` 

### ISSUE THREAD

**Issue by cyyzero** [apptainer/apptainer#430]
Hello, I have a question about function `fix_userns_devfuse_fd`.

https://github.com/apptainer/apptainer/blob/ba2337141b730c4f6f01bd5ed91051f7503a2776/cmd/starter/c/starter.c#L1073

```c
            /* re-open /dev/fuse file descriptors if any in the new user namespace */
            fix_userns_devfuse_fd(&sconfig->starter);
```

I am confused about the comment.  Why does  /dev/fuse need to be reopened in user namespace？Maybe just  to make it close-on-exec?

**Comment by DrDaveD** [comment]
@cclerget can correct me if I'm wrong, but I believe that file descriptors do not get passed from the CLI process to the starter process because the starter can run as suid.  So the starter can't rely on anything from the CLI process.

For more context: that code was inserted in apptainer/singularity#4953.

**Comment by cclerget** [comment]
@cyyzero Fuse file descriptors are all opened in stage 1, stage 1 is a forked step executing Go code in host user namespace, but opened `/dev/fuse` descriptors in the host user namespace couldn't be used inside a container user namespace for security reasons, that's why when a container is using a new container user namespace, we need to reopen them inside this new user namespace to make them usable and we also need to re-associate them to their previous file descriptor ID with dup3 call, re-association is important because the file descriptor ID is shared by at least two separate processes which require to operate on the same file descriptor ID
