### ISSUE TITLE
Attempting upgrade of Apptainer from 1.0.1 to 1.0.2 with plugins results in errors

### ISSUE THREAD

**Issue by treydock** [apptainer/apptainer#444]
### Version of Apptainer:

What version of Apptainer are you using? Run:

```
$ apptainer --version
1.0.1
```

### Expected behavior

I'd expect apptainer to allow me to install new version without plugins breaking install.  This worked with all Singularity 3.8.x releases.  I am using the log-plugin.

### Actual behavior

```
[root@pitzer-rw01 apptainer-1.0.2]# make -C ./builddir install
make: Entering directory `/opt/apptainer-1.0.2/builddir'
 MAN
mkdir -p /usr/share/man/man1
FATAL:   Failed to load plugins callbacks 'cli.Command': while initializing plugin "github.com/apptainer/apptainer/log-plugin": plugin.Open("/usr/libexec/apptainer/plugin/github.com/apptainer/apptainer/log-plugin/object"): plugin was built with a different version of package github.com/apptainer/apptainer/pkg/cmdline
exit status 255
make: *** [man] Error 1
make: Leaving directory `/opt/apptainer-1.0.2/builddir'
```

I'm able to kind of work around the problem by doing this:

```
# ./builddir/apptainer plugin compile examples/plugins/log-plugin
# ./builddir/apptainer plugin install examples/plugins/log-plugin/log-plugin.sif 
# make -C ./builddir install
```
These extra steps were not necessary with Singularity 3.8.x so not sure if this is expected behavior.

### Steps to reproduce this behavior

Install Apptainer 1.0.1 from source.
Install the log-plugin with Apptainer 1.0.1
Attempt to install Apptainer 1.0.2 from source

### What OS/distro are you running

RHEL 7.9

### How did you install Apptainer

This is source install with Go 1.17.8

**Comment by treydock** [comment]
I have a Puppet module to deploy Apptainer and part of the acceptance testing is installing Apptainer 1.0.0 with log-plugin and then upgrading to Apptainer 1.0.1 and adding log-plugin for that version and those operations inside container have no issues. If I update my acceptance tests to install 1.0.1 and then upgrade to 1.0.2, that's when the issue happens.  So the upgrade from 1.0.0 to 1.0.1 with log-plugin installed has no issues, the issue is 1.0.1 to 1.0.2.

As a work around I've updated my automation to first uninstall log-plugin before building apptainer 1.0.2, but ideally that wouldn't be necessary.

**Comment by DrDaveD** [comment]
I'm surprised you didn't see a problem upgrading from 1.0.0 to 1.0.1 or with singularity 3.8.x, because in my experience with singularity plugins this has always been an issue.   Because of golang 1.18, in 1.1.x dealing with plugins only gets worse, where compilation of plugins has to be done within the source tree of apptainer.  Both are limitations of the native go plugin framework that the apptainer plugin system is based on.  Since the framework is such a pain to work with, issue #419 was created.  I'll close this issue because I don't think there's anything we can do about it with the current framework.
