### ISSUE TITLE
Deal with moving ~/.singularity to ~/.apptainer

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#46]
Code in #3 changed ~/.singularity and $HOME/.singularity to ~/.apptainer and $HOME/.apptainer.  If that's going to stay that way, provide some kind of migration path or error exit if ~/.singularity exists but ~/.apptainer does not.

**Comment by DrDaveD** [comment]
Probably continue to use ~/.singularity if there is no ~/.apptainer, and print a deprecation warning.  If neither exists, create ~/.apptainer.

**Comment by ikaneshiro** [comment]
I do not think using `~/.singularity` if `~/.apptainer` doesn't exist will lead to a good user experience. In general I don't think we should be transparently writing to `~/.singularity`, so with that assumption we should only use it for reading.

There will be operations that require a user configuration directory to be available for writing, such as the `instance` command group which tracks state of spawned containers. This means we will need to automatically create a `~/.apptainer` directory.

With the proposed behavior, the use of a command group like `instance` will cause configuration that appeared to exist for the user to suddenly disappear because an `~/.apptainer` directory has been created. We should start with the assumption that an `~/.apptainer` directory exists, regardless of the existence of a `~/.singularity` directory.

We have two types of data within user home directories to consider and handle separately:
1. User configuration data (remotes, oci credentials, pgp keys)
2. User image cache data (cached SIF images, oci blobs)
3. Container state data (meta data of tracked container processes)


1. User configuration data
I think the best user experience will be to offer migration commands to update user configurations in a new, potentially empty `~/.apptainer` directory from a `~/.singularity` directory if it exists.

The two major types of user configuration could be migrated with the following commands:
```
apptainer legacy migrate gpgkeys
apptainer legacy migrate remotes 
```

2. User image cache data
It would be ideal to merge image cache data in `~/.apptainer` and `~/.singularity` into a single cache without data duplication.
Unfortunately, the way the image cache packages in use by Apptainer are not designed to allow merging of multiple image or blob caches for use during an operation. This would take significant effort to update internal and external packages to make a reality.

Instead I propose that Apptainer automatically uses `~/.apptainer` for image/blob caching and we communicate to users that they can use the an existing cache created from a Singularity installation by simply setting `APPTAINER_CACHEDIR=~/.singularity`.

3. Container state data
This should always be under `~/.apptainer` for containers spawned by Apptainer. It does not make sense to me to try to guarantee that instances, and their resulting state, created by an Apptainer installation can be managed by a Singularity installation. And vice versa.


Based off of these thoughts, I will create a pr for commands to migrate user configuration data

**Comment by gmkurtzer** [comment]
I feel like we already discussed this, and as I recall (which I preferred). I think it was something like:

```
if test -d ~/.apptainer; then
    # all is well with the world.
else
   if test -d ~/singularity && some sort of version check; then
      echo "Migrating Singularity configuration directory to Apptainer"
      # Obviously do something better than this, so we only copy configs, keys, etc.
      cp -rap ~/.singularity ~/.apptainer
   else
      # Create new Apptainer directory
   fi
fi

# Always use ~/.apptainer ...
```

I am not personally a fan of migrating configurations via a CLI, as people will forget and it isn't transparently compatible.

**Comment by ikaneshiro** [comment]
My biggest concern was around what appeared to proposed behavior that would write to `~/.singularity`, this idea ensures that does not happen and more automatic for users. I will use this approach instead.

**Comment by DrDaveD** [comment]
I thought the consensus of the discussion was more like what I wrote above, but I'm good with the way Greg described it.  Watch out for cases of non-writable or non-existent home directories, as I know that we have had issues with those in the past and some batch systems run that way.
