### ISSUE TITLE
transition singularity image from setuid to nosetuid

### ISSUE THREAD

**Issue by simonleary-umass-edu** [apptainer/apptainer#544]
A user of mine is migrating from another cluster, and wants to take his .simg with him.
But when he tries to use his image, it fails I think because our singularity was configured with nosetuid, while his was not.
```
[91mERROR : No setuid installation found, for unprivileged installation use: ./mconfig --without-suid
```
Is there a way for him to rebuild his image in a way that it will play nice with our installation of singularity?

**Comment by DrDaveD** [comment]
Images aren't inherently privileged or unprivileged.  The ".simg" name implies his image is old enough to have been built with singularity-2 (not necessarily, people can call files anything they want but newer images are usually .sif), but even if I create an image with singularity-2 I can still run it on the latest singularity-3.  When I do it unprivileged I get a message
```
INFO:    Converting SIF file to temporary sandbox...
```
but it works.  What version of singularity do you have, and are there any non-standard options set?

All currently released versions of singularity and apptainer require suid in order to directly mount any container image file. The next release of apptainer will not require it, instead mounting the image with squashfuse, so it will not need to convert it to a sandbox.
