### ISSUE TITLE
The `--nvccli` option can now be made usable without `--fakeroot`

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#593]
With apptainer-1.1.0-rc.1, the `--nv --nvccli` options without `--fakeroot` require using `--writable`, but now `--writable-tmpfs` could be used instead in order to automatically create bind mountpoints.  (Using `--fakeroot` automatically implies `--writable-tmpfs`).  When I change the code to allow `--writable-tmpfs`, I found that the invocation of `nvidia-container-cli` was missing one more ambient cap, CAP_NET_ADMIN.

Also I think that `--nvccli` should imply `--nv`, because currently if you just use `--nvccli` it is silently ignored.

**Comment by sawyermade** [comment]
Okay, so I installed apptainer-1.1.0.rc.2-1.x86_64.rpm and when trying to run --nvccli I get this error: 
[nsambhu@home1 singularity_shit]$ apptainer run --nvccli tensorflow_latest-gpu
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
INFO   : A system administrator may need to enable user namespaces, install
INFO   :   apptainer-suid, or compile with ./mconfig --with-suid
ERROR  : Failed to create user namespace: user namespace disabled

Then after installing apptainer-suid-1.1.0.rc.2-1.x86_64.rpm and running it again I get this error:
[nsambhu@home1 singularity_shit]$ apptainer run --nvccli tensorflow_latest-gpu
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   nvidia-container-cli not allowed in setuid mode

If setting setuid to no in the apptainer.conf, I get the first error again. So basically it's saying that it can't run no matter what haha. Not sure if this is possibly an error in the code where it checks setuid or something but I thought the whole point of the merge was in order to allow it to run in setuid mode without --fakeroot.

Also, I built the tensorflow sandbox with --fix-perms as well:
$ apptainer build --sandbox --fix-perms tensorflow_latest-gpu docker://tensorflow/tensorflow:latest-gpu

**Comment by DrDaveD** [comment]
It will run if user namespaces are enabled. In fact it is easier to use with 1.1.0 than it is in 1.0.0 because of the new unprivileged features, but it requires user namespaces.

Unfortunately that message about optionally installing apptainer-suid or compiling with `mconfig --with-suid` comes from a low layer of the code (in starter.c) that does not know that `--nvccli` is only supported unprivileged, it just knows that user namespaces failed. It is only an experimental option so I don't think it's worth trying to change that message.

`--nvccli` is not supported in suid mode because it would have required running an external program as root, and we don't trust that.
