### ISSUE TITLE
 allow for fakeroot subuid/subgid mappings shorter than 65536 IDs

### ISSUE THREAD

**Issue by thdesy** [apptainer/apptainer#691]
Apptainer re-post of issue https://github.com/apptainer/singularity/issues/5932  @ECoulter @LaHaine

### Version of Apptainer

apptainer version 1.1.0~rc.2-1.el7
Expected behavior

Running singularity with a limited range of subuid/subgid for fakeroot.
We would like to enable fakeroot for our users. But we would like to keep the mapped IDs constraint and consistent with our campus-wide uid policy to avoid potential clashes. To do so, we reserved a blcok of UIDs in our ID namespace to be used only for such dynamic, container-flavoured mappings, that are not to be used for other purposes or actual users. Since the block is currently limited in its range (100k), we can allocate only a limited sub-block of IDs to each others.

```
> head  -n4 /etc/subuid
# Managed by Puppet (subuid)
# Do NOT edit, changes will be overwritten!
foouser:23000000:100
bazuser:23000100:100
...
```

```
> head  -n4 /etc/subdid
# Managed by Puppet (subuid)
# Do NOT edit, changes will be overwritten!
foouser:23000000:100
bazuser:23000100:100
...
```

Since we assume, that users will need during container builds or runs of their analyses containers only a few UIDs, it would be nice, if an admin could allow for smaller sub-ID ranges.

**Comment by DrDaveD** [comment]
@LaHaine that is indeed a bug.  Please create a separate issue for that.

@thdesy as was stated in a [comment on the previous issue](https://github.com/apptainer/singularity/issues/5932#issuecomment-1105482414), because the "nobody" id is 65534 there really ought to be a mapping of that so it doesn't become the same "nobody" in different containers.  So I don't think it's a good idea to support less than 64k.  Hopefully you're aware that with apptainer-1.1.0 the subuid/subgid mappings will not be necessary (they're only nice to have).

**Comment by LaHaine** [comment]
I have opened a separate issue here: https://github.com/apptainer/apptainer/issues/692

**Comment by thdesy** [comment]
@DrDaveD thanks for the reassurance :) We are preparing for switching to Apptainer 1.1, so that it should be no problem.

**Comment by DrDaveD** [comment]
I wrote above:
> ... as was stated in a [comment on the previous issue](https://github.com/apptainer/singularity/issues/5932#issuecomment-1105482414), because the "nobody" id is 65534 there really ought to be a mapping of that so it doesn't become the same "nobody" in different containers. So I don't think it's a good idea to support less than 64k. 

While reconsidering this and re-reading the referenced document (https://systemd.io/UIDS-GIDS/, section "Considerations for container managers") I now realize that my previous explanation was incorrect.  The issue is not the id 65534 becomes the same in containers run by different users.  The issue is that systemd and probably other applications expect to be able to use the id 66534.  If there are less than that many ids mapped, the id 65534 becomes unusable.  In that case if you do an `ls` or `stat()` on any file that is owned by an id that is not mapped it will still show as 65534, but if you try to create a file (for example) owned by 65534 that becomes not allowed if it is not mapped.  I verified that it is allowed to chown a file to 65534 if only if that id is mapped.  So the bottom line is that 65536 ids should be allocated for every use so that it is possible to run systemd or similar applications that make use of id 65534.

podman does not require 65536 ids, it allows any number, so perhaps apptainer should allow it too (especially since it's even less likely that someone will run systemd inside apptainer than inside podman).  On the other hand, system administrators that choose to allocate less than 65536 will eventually run into a problem when one of their users wants to run systemd in a container, so in a way apptainer is doing them a favor by requiring 65536 when /etc/subuid and /etc/subgid are set up.

**Comment by moskalenko** [comment]
> I wrote above:
> 
> > ... as was stated in a [comment on the previous issue](https://github.com/apptainer/singularity/issues/5932#issuecomment-1105482414), because the "nobody" id is 65534 there really ought to be a mapping of that so it doesn't become the same "nobody" in different containers. So I don't think it's a good idea to support less than 64k.
> 
> While reconsidering this and re-reading the referenced document (https://systemd.io/UIDS-GIDS/, section "Considerations for container managers") I now realize that my previous explanation was incorrect. The issue is not the id 65534 becomes the same in containers run by different users. The issue is that systemd and probably other applications expect to be able to use the id 66534. If there are less than that many ids mapped, the id 65534 becomes unusable. In that case if you do an `ls` or `stat()` on any file that is owned by an id that is not mapped it will still show as 65534, but if you try to create a file (for example) owned by 65534 that becomes not allowed if it is not mapped. I verified that it is allowed to chown a file to 65534 if only if that id is mapped. So the bottom line is that 65536 ids should be allocated for every use so that it is possible to run systemd or similar applications that make use of id 65534.
> 
> podman does not require 65536 ids, it allows any number, so perhaps apptainer should allow it too (especially since it's even less likely that someone will run systemd inside apptainer than inside podman). On the other hand, system administrators that choose to allocate less than 65536 will eventually run into a problem when one of their users wants to run systemd in a container, so in a way apptainer is doing them a favor by requiring 65536 when /etc/subuid and /etc/subgid are set up.

In our case it is more likely that a container is run by the host systemd. It'd be great to use the same concise /etc/subuid and /etc/subgid (with 2-3k sub ids at most) that we already use for podman.

Cheers,

Alex

**Comment by thdesy** [comment]
Hi @moskalenko ,

are you sure, that your podman set up is safe?
When I played with ranges of users in container with different runtimes, the behaviour was like @DrDaveD described.

Cheers,
  Thomas

**Comment by DrDaveD** [comment]
If somebody wants to make a pull request that enables this functionality via a non-default apptainer.conf setting that is commented with strong warnings, I would be OK with that.
