### ISSUE TITLE
retain backward compatibility for environment variables

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#7]
The legacy singularity supports environment variables named "SINGULARITY_*" and "SINGULARITYENV_*"

Apptainer supports environment variables named "APPTAINER_*" and "APPTAINERENV_*"

Proposed:

1. When the inherited environment has APPTAINER variable of same name suffix as a set SINGULARITY environment variable, the APPTAINER value shall have precedence. 

2. When a SINGULARITY environment variable is set, and the APPTAINER environment with the same suffix is not set, copy the value of the SINGULARITY environment variable to a newly created APPTAINER variable with same name suffix.

3. When creating the environment for a child process, enumerate all APPTAINER variable values from (1, 2) above, and create a new set of SINGULARITY environment variables with the same value and name suffix as the APPTAINER variable.

**Comment by truatpasteurdotfr** [comment]
- emit a warning for 1) 
- emit an info for 2)
ymmv, but that look consistent to me.

**Comment by DrDaveD** [comment]
I think the plan is to only support environment variables starting with SINGULARITY, at least at first.

**Comment by DrDaveD** [comment]
I think that supporting any APPTAINER* variable should not be in Apptainer 1.0.0, and we can consider it for Apptainer 1.1.0.

**Comment by PaulCharlton** [comment]
noting ongoing governance discussion via the Apptainer/development slack channel

**Comment by gmkurtzer** [comment]
> 1. When the inherited environment has APPTAINER variable of same name suffix as a set SINGULARITY environment variable, the APPTAINER value shall have precedence.

I concur with @truatpasteurdotfr, that should emit a warning.

> 2. When a SINGULARITY environment variable is set, and the APPTAINER environment with the same suffix is not set, copy the value of the SINGULARITY environment variable to a newly created APPTAINER variable with same name suffix.

I concur with @truatpasteurdotfr again, but this should also be a warning of depreciation. 

> 3. When creating the environment for a child process, enumerate all APPTAINER variable values from (1, 2) above, and create a new set of SINGULARITY environment variables with the same value and name suffix as the APPTAINER variable.

Yes. This is a good idea to ensure compatibility for all cases.

**Comment by gmkurtzer** [comment]
> I think that supporting any APPTAINER* variable should not be in Apptainer 1.0.0, and we can consider it for Apptainer 1.1.0.

These are not major or high risk changes, I would strongly push for them to be in 1.0.0 so the entire 1.x series won't have any major breaking changes after the first release.

It seems that the OP's proposal satisfies pretty much all edge cases and backwards compatibility that will come up.

**Comment by DrDaveD** [comment]
Ok, then I think that this is one of the most significant remaining pieces of work for 1.0.0 and so should probably be given a high priority to complete.

e2e tests may be a very challenging piece of this work.  I think that probably all the variables should be tested under both names.   I wonder if it would make sense to run all the e2e tests that make use of variables in a separate parallel CI test for the alternate prefix, rather than significantly extending the length of the existing e2e CI test.

I don't know if the algorithm of the relationship between corresponding variables needs to be tested for every variable, if that algorithm is able to be put into a function that every case uses, although it should be tested. I guess for that matter, if we can ensure that every use of an environment variable uses a common function, maybe we can also get away without testing every variable.  I would worry however that some use cases might slip through without using the common function.

**Comment by PaulCharlton** [comment]
@DrDaveD for the inbound environment variables, they go through a single function for the most part (and the remainder should be re-routed via that function)

Also, this issue should be broken into two separate issues.
1. inbound environment variables
2. published environment variables for child/exec'd processes
