### ISSUE TITLE
Unable to use SSH features due to bad ownership nobody:nobody on /etc/ssh/ssh_config.d/*

### ISSUE THREAD

**Issue by milljm** [apptainer/apptainer#736]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).
```bash
$ apptainer --version
apptainer version 1.1.0-1
```
### Expected behavior
Able to use SSH features while inside container (git clone git@, ssh, etc)

### Actual behavior
Unable to utilize SSH features while inside container.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Create a Rocky-8 container and launch said container with 1.1 Apptainer. Attempt to use SSH.

Minimal definitions file:
```def
BootStrap: yum
OSVersion: 8
MirrorURL: https://download.rockylinux.org/pub/rocky/%{OSVERSION}/BaseOS/$basearch/os/
Include: yum

%post
    yum -y groupinstall "Development Tools"
```

Build/Run:
```bash
apptainer build --fakeroot rocky-8.sif rocky-8.def
apptainer shell rocky-8.sif
```
Note: I've tried with and without --fakeroot options

Attempt to use SSH:
```bash
Apptainer> ssh localhost
Bad owner or permissions on /etc/ssh/ssh_config.d/05-redhat.conf
```

Ownership while using container with Apptainer 1.1:
```pre
Apptainer> ls -latrh /etc/ssh/ssh_config.d/
total 512
-rw-r--r-- 1 nobody nobody 831 Apr 12 01:26 05-redhat.conf
```
Ownership while using the same container with Apptainer 1.0.3-1:
```pre
Apptainer>  ls -latrh /etc/ssh/ssh_config.d/
total 1.0K
-rw-r--r-- 1 root root 831 Oct 10  2021 05-redhat.conf
```
(SSH features in this case work)

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

### How did you install Apptainer

RPM:
```bash
dnf install -y https://github.com/apptainer/apptainer/releases/download/v1.1.0/apptainer-1.1.0-1.x86_64.rpm
```

**Comment by milljm** [comment]
I was reluctant to post such an issue, as I would expect little 'ol me can't be the only one running into it.
Perhaps this is limited to Rocky-8. I'll try building a Rocky-9 image and report back.

I've tried re-building my sif image from my definition file using latest Apptainer to no effect.

**Comment by milljm** [comment]
I figured it out. I need to supply --fakeroot as I shell into the container. Cheers!

```bash
apptainer shell | exec --fakeroot rocky-8
```

**Comment by milljm** [comment]
Re-opening, as I am not a fan of entering a container with an ID of 0 (root), even though I know that does not mean I also have root on the host machine.

```bash
Apptainer> id
uid=0(root) gid=0(root) groups=0(root)
Apptainer> exit
```

**Comment by DrDaveD** [comment]
Thanks for posting the issue, it's not something I had thought to test, and it is unfortunate because I don't know a good solution for it.

The [ssh source code](https://github.com/openssh/openssh-portable/blob/master/readconf.c#L2255) is checking for either uid 0 or the current user id.  With unprivileged user namespaces (and without fakeroot), it's not an option for it to show up as uid 0, because the only mapped user id is the current user id; everybody else is mapped to `nobody`.

One way around it is to run with `--fakeroot` as you saw; that makes the files appear to be owned as uid 0.  The reason why it is not working without fakeroot is that the `squashfuse_ll` program does not support the `-o uid=NN` option, so apptainer cannot tell it to show all files as owned by you.  Apptainer will pass that option if the program is `squashfuse`, because that supports it.  I just verified it by temporary renaming the `squashfuse_ll` programs.  The `squashfuse_ll` program has so much better performance than `squashfuse` that it's really not worth considering making it the default because of this issue.

I looked briefly at possibly making a patch to `squashfuse_ll` to add this option, but at first glance it looked like the low-level FUSE API that `squashfuse_ll` uses may make it so that is not even possible.  The `-o uid=NN` option in `squashfuse` is in fact implemented by the FUSE library, not `squashfuse` itself.

The only other idea I have for a workaround at this point is that the problem does not happen with sandboxes, which you can get for example temporarily with the `--unsquash` option.   I suppose it would also be possible to make an action command option to have it prefer `squashfuse` over `squashfuse_ll`, although that would be a bit of a challenge to implement because of the internal image driver api that is being used for that.

**Comment by DrDaveD** [comment]
> I looked briefly at possibly making a patch to squashfuse_ll to add this option, but at first glance it looked like the low-level FUSE API that squashfuse_ll uses may make it so that is not even possible. 

No I think I was remembering wrong.  I do see the implementation of the `stat` function there returning a `uid` and `gid`, so  `-o uid` and `-o gid` options probably could be implemented.  Then the next question would be how Apptainer could figure out whether or not to pass them depending on the version of `squashfuse_ll`.

**Comment by DrDaveD** [comment]
I made a [squashfuse pull request](https://github.com/vasi/squashfuse/pull/77) to add these options to the low level interface.  Apptainer could parse the help message looking for the option when deciding whether or not to invoke it with `squashfuse_ll`, and it could include that patch with the squashfuse that it builds in rpm & debian packaging.

**Comment by milljm** [comment]
Running in sandbox mode is an option I can explore among our CI operations. Thank you for suggesting it!

**Comment by jcphill** [comment]
@milljm I just wanted to suggest ``--bind ~/.ssh/config:/etc/ssh/ssh_config.d/05-redhat.conf:ro`` as an alternative workaround.

**Comment by milljm** [comment]
I can confirm release 1.1.3-1 solves our issue. Cheers!

**Comment by NamjaeChoi** [comment]
I'm still seeing this issue in Apptainer 1.1.4.
