### ISSUE TITLE
`open /var/lib/containers/: permission denied`

### ISSUE THREAD

**Issue by multimeric** [apptainer/apptainer#758]
### Version of Apptainer

1.1.0

### Expected behavior

I expected apptainer to pull docker images without trying to access system directories such as `/var/lib/containers`

### Actual behavior

```
FATAL:   While performing build: conveyor failed to get: initializing source oci:/home/users/allstaff/milton.m/.apptainer/cache/blob:d7f4aada301c0f13d93ceed62fef318c195c38bf
430fc8bfbdf1d850514422ff: copying system image from manifest list: reading signatures: open /var/lib/containers/sigstore/library/busybox@sha256=505e5e20edbb5f2ac0abe3622358d
af2f4a4c818eea0498445b7248e39db6728/signature-1: permission denied
```

So, when trying to build as an unprivileged user, apptainer is trying to read from `/var/lib/containers`, which is not globally readable. I'm wondering if this is controlled by some configuration option, and if so, how can I change this, so that I can build containers without root.

### Steps to reproduce this behavior

Not entirely sure what config lead to this happening, but the commands I ran were:

```
$ cat test.def
Bootstrap: docker
From: busybox:1.35.0
$ apptainer build test.cif test.def                                                                        
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    fakeroot command not found
INFO:    Installing some packages may fail
INFO:    Starting build...
Getting image source signatures
FATAL:   While performing build: conveyor failed to get: initializing source oci:/home/users/allstaff/milton.m/.apptainer/cache/blob:d7f4aada301c0f13d93ceed62fef318c195c38bf
430fc8bfbdf1d850514422ff: copying system image from manifest list: reading signatures: open /var/lib/containers/sigstore/library/busybox@sha256=505e5e20edbb5f2ac0abe3622358d
af2f4a4c818eea0498445b7248e39db6728/signature-1: permission denied
```

### What OS/distro are you running
CentOS 7

### How did you install Apptainer

Not sure, it was installed as a system module.

**Comment by multimeric** [comment]
After some discussion, we're thinking that maybe `apptainer` is looking for `/var/lib/containers` and tries to read from it *if it exists*, but otherwise skips it. This problem only seems to occur on our login nodes, which do have a `/var/lib/containers`, but goes away on our compute nodes which do not. Could the bug fix for this be to only try reading from this directory if it exists *and we have read access to it*?

**Comment by DrDaveD** [comment]
Thanks for the report!

Apptainer does use an OCI library for downloading from docker, so your hypothesis is feasible.  I do have `/var/lib
/containers` on my system but no `/var/lib/containers/sigstore`.  From googling, it looks like that might be created when running `podman image sign` as root.  Formerly it wouldn't have been noticed if there was a permission problem reading from there because builds used to have to be done as root.  Oh, it could be that it would have been a problem if someone was running with older version `--fakeroot` and `/etc/sub[ug]id` mappings. 

I can reproduce the problem by `mkdir /var/lib/containers/sigstore; chmod 700 /var/lib/containers/sigstore`.  Interestingly, it does not happen when `/etc/sub[ug]id` mappings has been set. We'll have to look into seeing if there's a way to get the library to behave the same with the other fakeroot modes.

**Comment by multimeric** [comment]
Yes I should have mentioned, but our installation is unprivileged (not running as root), and we don't have any user mappings setup, nor do we have the fakeroot binary, but apptainer is running in `--fakeroot` mode (implicitly). As you have noted these are probably the conditions that cause this error to exist.

**Comment by sbutcher** [comment]
Can confirm this issue on our HPC. We had a few nodes with `/var/lib/containers/cache` existent. On a node without this, the builds work
