### ISSUE TITLE
[feature request]  Support Intel GPU

### ISSUE THREAD

**Issue by houyushan** [apptainer/apptainer#841]
singularity version 3.7.1

Use Intel GPU（[XPU](https://www.intel.com/content/www/us/en/software/xpu-manager.html) )

my product needs to use the singularity/apptainer to use the Intel XPU (the latest Intel GPU for AI training). Is there a command like -- nv to support it at present, or will future versions provide similar commands? When will it be?

**Comment by DrDaveD** [comment]
There's no specific plan for that.  Someone who has access to a machine with the GPU would need to be interested enough to submit a pull request. It's also possible that either `--nv` or `--rocm` could be adapted to work with that GPU by updating `nvliblist.conf` or `rocmlist.conf` in `/etc/apptainer`.

**Comment by lnauta** [comment]
At the SURF NREN we now are experimenting with the Intel Max 1100 and ran into this issue. On the HPC systems we use apptainer and having this flag would be greatly appreciated.

**Comment by GodloveD** [comment]
@lnauta are you able to identify what library or libraries are missing that need to be in the container to leverage the intel GPU?  Maybe by installing `strace` into the container and using it to find failed library calls?

**Comment by lnauta** [comment]
My apologies, it turns out the container I was using did not include `xpu` because I fetched the latest version (2.2.0), while version 2.1.10 does have this flag enabled. With the xpu-version there was no need for any flags or special behaviour, it works out of the box.

Building it with `apptainer build intel-optimized-pytorch-2.1.10-xpu-pip-base.sif docker://intel/intel-optimized-pytorch:2.1.10-xpu-pip-base` and running `apptainer shell intel-optimized-pytorch-2.1.10-xpu-pip-base.sif` my pytorch tests ran without a hitch and comparing with and without the GPU enabled (through SLURM) there is a 200x speedup of a matmul test, confirming it is indeed using the GPU (tests taken from https://pytorch.org/tutorials/recipes/recipes/benchmark.html)

If more information is needed, I can provide it.
