### ISSUE TITLE
singularity: root filesystem extraction failed: extract command failed: ERROR : Failed to create user namespace

### ISSUE THREAD

**Issue by ElenaSLuis** [apptainer/apptainer#871]
Hey! I'm using singularity with version 3.7.1 in order to use Demuxify.sif.

I install with conda environment:
conda install -c conda-forge singularity

the code problem is:
$ singularity exec Demuxafy.sif Combine_Results.R -h
INFO: Converting SIF file to temporary sandbox...
FATAL: while extracting Demuxafy.sif: root filesystem extraction failed: extract command failed: ERROR : Failed to create user namespace: user namespace disabled
: exit status 1

Thank youu in advance!

Elena

**Comment by DrDaveD** [comment]
That installation of singularity apparently requires unprivileged user namespaces.  You didn't mention your host operating system, but if it is RHEL7-based that is something that needs to be enabled.  See https://apptainer.org/docs/admin/main/user_namespace.html#user-namespace-requirements

**Comment by wjzwjz5** [comment]
hey, I have seem problem,I could use singularity and Demuxafy.sif before.But after I build my conda environment,it cannot work.
The problem is :
FATAL:   while extracting Demuxafy.sif: root filesystem extraction failed: extract command failed: FATAL:   container creation failed: open /etc/resolv.conf: no such file or directory
: exit status 255
Thanks!

**Comment by DrDaveD** [comment]
That's a different error. Please create a separate issue and provide all your particulars including host OS and complete steps to reproduce.
