### ISSUE TITLE
Feature request: squashfs fuse alternatives 

### ISSUE THREAD

**Issue by zeronewb** [apptainer/apptainer#881]
squashfsfuse rotting a bit .

Possible candidates dwarfs[1].
[1] https://github.com/mhx/dwarfs

**Comment by DrDaveD** [comment]
That's not only a squashfuse alternative, it is a different filesystem format.  We can't make incompatible SIF files at this point.  It's also not clear that dwarfs is a production quality system.  It's main space savings comes from duplicated files, and I don't expect a whole lot of duplicated file within a single container.  Across containers, yes, that's why having unpacked containers in the [CernVM FileSystem](https://cernvm.cern.ch/fs/) is huge space saver.  

We have offered to take over ownership of squashfuse but so far the maintainer hasn't given us an answer.
