### ISSUE TITLE
Installing CUDA or ROCm libraries in a container

### ISSUE THREAD

**Issue by NamjaeChoi** [apptainer/apptainer#928]
Hello,
I'm a beginner user of Apptainer.

When reading the GPU support part of the manual (https://apptainer.org/docs/user/main/gpu.html#), I understood it as if CUDA or ROCm libraries should be installed in the host and they cannot be installed in a container.
I think libraries and drivers are independent, so I don't see any problem in installing the libraries in a container.
What would be the problem if I install the libraries in a container? Would I be unable to see the GPU devices?

Thank you.

**Comment by DrDaveD** [comment]
I don't know the answer.  Since this is more of a usage question than an issue with apptainer, I suggest you try asking the community either on the mailing list or the slack channel.  Links are at https://apptainer.org/help.

**Comment by NamjaeChoi** [comment]
Oh yes, I was looking for the user community. Thanks.

**Comment by GodloveD** [comment]
Hi @NamjaeChoi.  I answered your question in the Slack community channel but I'll post it here too for added visibility:

First, it is important to specify which libraries you are referring to.  The CUDA libraries are independent of the driver (as long as the driver version is new enough to provide support for whatever version of CUDA you are using) and should be installed in the container.  But the driver itself also has libraries which are tightly coupled to the driver kernel module.  So you don't want to install those in your container.  Best case they will be useless garbage that will be ignored when you add the `--nv`  option.  Worst case they will render your container inoperable if you run it on a host with a different driver version.

Unfortunately, NVIDIA muddies the water in a few different ways making it confusing as to which libraries are part of the CUDA installation and which are part of the driver installation.  For instance `libcuda.so` is actually a _driver_ library providing a way for CUDA to access the GPU kernel module.  And NVIDIA packages the driver `.run`  file inside the CUDA `.run` file so that when you install CUDA, by default it will also try to update your driver.  Don't fall for these shenanigans!  :smile:  You can see which libraries apptainer will pull in from the host in [`etc/apptainer/nvliblist.conf`](https://github.com/apptainer/apptainer/blob/main/etc/nvliblist.conf).  Those are the libraries that you want to avoid installing in your container to keep it portable.  And you should extract the contents of the CUDA `.run` file and toss the driver installation file before installing CUDA in your container.
