### ISSUE TITLE
Regression in 1.1.4: cannot run in htcondor with input file transfer

### ISSUE THREAD

**Issue by LaHaine** [apptainer/apptainer#958]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```apptainer version 1.1.4-1.el7```

### Expected behavior

It should start without errors

### Actual behavior
```
FATAL:   While initializing: couldn't parse configuration file etc/apptainer/apptainer.conf: open etc/apptainer/apptainer.conf: no such file or directory

```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

This is started from a HTCondor job that was working fine for years. A minimal condor submit file:
```
output=folding.$(ClusterId).$(ProcId).out
error=folding.$(ClusterId).$(ProcId).err
should_transfer_files=YES
transfer_input_files=test.sh
executable=/usr/bin/apptainer
queue
```
It is working fine if ```should_transfer_files=NO``` is set. 

The difference between the runs with transfer disabled vs. enabled is the initial job directory.

It is also working fine if apptainer isn't started directly but from a minimal script file test.sh:
```
#!/bin/bash
/usr/bin/apptainer
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
EPEL rpm package

**Comment by DrDaveD** [comment]
This does not give enough information to reproduce the problem.  How is htcondor installed and configured?  What is the content of test.sh?

**Comment by DrDaveD** [comment]
This may be related to #932 which has a fix in #934.

**Comment by LaHaine** [comment]
I have tried with the patch from #934, but it didn't help. Also, in #932 a non-standard libexecdir was used, this is not the case with the EPEL package of apptainer.

I know, it is hard to setup a htcondor just for testing. But isn't it strange that the workaround is to just start apptainer from the simple bash script seen above instead of from htcondor?

**Comment by DrDaveD** [comment]
The rpm package does set a bunch of mconfig options in addition to `--prefix` so that's why I thought it might be related.  #934 addressed what changed in 1.1.4 but possibly it didn't address everything related to that change.

Setting up htcondor is not that hard for me, I already happen to have a standalone instance.  Oh I didn't notice that you had already included the contents of test.sh.  Ok I am now able to reproduce the problem, and now I realize that the contents of test.sh doesn't matter anyway, it's the executable that matters.

**Comment by DrDaveD** [comment]
Ok by making an executable that's my own script with contents
```
#!/bin/bash
echo "ARGS: $0 $@"
```
I see this output
```
ARGS: /var/lib/condor/execute/dir_614140/condor_exec.exe
```
which if it's a copy of apptainer it's going to make apptainer 1.1.4 think that it has been relocated.  That's really a bad way to run apptainer, because it only copies the frontend executable without all the other support files.  If you would use this to submit to a worker node that has its own installation of apptainer, it could really mess things up, running a different version of the apptainer executable than all the support files.

So, the conclusion is that it's a bad condor submit file.  Yes the behavior of apptainer changed in 1.1.4, but it caught a programming error that would have eventually probably hit you in other more subtle ways.

**Comment by DrDaveD** [comment]
Nevertheless, it did reveal a subtle apptainer 1.1.4 bug in that it should not have treated the installed prefix as the empty string.  I'm working on a fix for that and I think the best thing to do is to die with a more helpful error message, rather than restoring the previous behavior.

**Comment by DrDaveD** [comment]
Actually it turned out to break other things to make it die more helpfully, so instead I restored the previous behavior of using the compiled-in prefix.

**Comment by ShamrockLee** [comment]
I observer the bug when trying to package Apptainer 1.1.4 for [Nixpkgs](https://github.com/NixOS/nixpkgs). It happens when `/etc/apptainer` is not available, which is not HTCondor specific.

Thanks for addressing this issue!
